/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\themes\neutral\neutralTheme.ts
 * Command: astryx theme build src\themes\neutral\neutralTheme.ts
 * CLI: @astryxdesign/cli@0.5.0
 * Core: @astryxdesign/core@0.5.0
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
