import React from 'react';
import type {IconRegistry} from '@astryxdesign/core/Icon';

import {
  X,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  Check,
  CheckCircle,
  XCircle,
  AlertTriangle,
  Info,
  Calendar,
  Clock,
  ExternalLink,
  Menu,
  MoreHorizontal,
  Search,
  ArrowUp,
  ArrowDown,
  ArrowUpDown,
  Filter,
  EyeOff,
  Columns,
  Copy,
  CheckCheck,
  Wrench,
  Square,
  Mic,
} from 'lucide-react';

const iconProps = {
  size: '1em',
  strokeWidth: 2,
};

export const supabaseIconRegistry: IconRegistry = {
  close: <X {...iconProps} />,
  'chevron-down': <ChevronDown {...iconProps} />,
  'chevron-left': <ChevronLeft {...iconProps} />,
  'chevron-right': <ChevronRight {...iconProps} />,
  'chevrons-left': <ChevronsLeft {...iconProps} />,
  'chevrons-right': <ChevronsRight {...iconProps} />,
  check: <Check {...iconProps} />,
  'check-circle': <CheckCircle {...iconProps} />,
  'x-circle': <XCircle {...iconProps} />,
  'alert-triangle': <AlertTriangle {...iconProps} />,
  info: <Info {...iconProps} />,
  calendar: <Calendar {...iconProps} />,
  clock: <Clock {...iconProps} />,
  'external-link': <ExternalLink {...iconProps} />,
  menu: <Menu {...iconProps} />,
  'more-horizontal': <MoreHorizontal {...iconProps} />,
  search: <Search {...iconProps} />,
  'arrow-up': <ArrowUp {...iconProps} />,
  'arrow-down': <ArrowDown {...iconProps} />,
  'arrow-up-down': <ArrowUpDown {...iconProps} />,
  filter: <Filter {...iconProps} />,
  'eye-off': <EyeOff {...iconProps} />,
  columns: <Columns {...iconProps} />,
  copy: <Copy {...iconProps} />,
  'check-check': <CheckCheck {...iconProps} />,
  wrench: <Wrench {...iconProps} />,
  square: <Square {...iconProps} />,
  mic: <Mic {...iconProps} />,
};
