/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\themes\supabase\supabaseTheme.ts
 * Command: astryx theme build src\themes\supabase\supabaseTheme.ts
 * CLI: @astryxdesign/cli@0.5.0
 * Core: @astryxdesign/core@0.5.0
 */

import { supabaseIconRegistry } from './icons';
/**
 * supabase theme — built by `pnpm exec astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { supabaseTheme } from './supabase';
 *   import './supabase.css';
 */
export const supabaseTheme = {
  name: 'supabase',
  __built: true,
  tokens: {
    "--font-size-4xs": "0.375rem",
    "--font-size-3xs": "0.4375rem",
    "--font-size-2xs": "0.5625rem",
    "--font-size-xs": "0.625rem",
    "--font-size-sm": "0.8125rem",
    "--font-size-base": "0.9375rem",
    "--font-size-lg": "1.125rem",
    "--font-size-xl": "1.375rem",
    "--font-size-2xl": "1.625rem",
    "--font-size-3xl": "1.9375rem",
    "--font-size-4xl": "2.3125rem",
    "--font-size-5xl": "2.8125rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-semibold)",
    "--text-heading-1-leading": "1.3846",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-semibold)",
    "--text-heading-2-leading": "1.4545",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-bold)",
    "--text-heading-3-leading": "1.5556",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-bold)",
    "--text-heading-4-leading": "1.6",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-semibold)",
    "--text-heading-5-leading": "1.5385",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-semibold)",
    "--text-heading-6-leading": "1.6",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.6",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.5556",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.6",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.6",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.5385",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.2444",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.2973",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.4194",
    "--duration-fast-min": "115ms",
    "--duration-fast": "150ms",
    "--duration-fast-max": "200ms",
    "--duration-medium-min": "150ms",
    "--duration-medium": "200ms",
    "--duration-medium-max": "265ms",
    "--duration-slow-min": "300ms",
    "--duration-slow": "400ms",
    "--duration-slow-max": "535ms",
    "--font-family-body": "Inter, Inter, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
    "--font-family-heading": "Inter, Inter, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
    "--font-family-code": "ui-monospace, \"SF Mono\", Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace",
    "--color-syntax-keyword": "light-dark(#3ecf8e, #72e3ad)",
    "--color-syntax-string": "light-dark(#10b981, #6ee7b7)",
    "--color-syntax-comment": "light-dark(#64748b, #94a3b8)",
    "--color-syntax-number": "light-dark(#f59e0b, #fbbf24)",
    "--color-syntax-function": "light-dark(#3b82f6, #60a5fa)",
    "--color-syntax-type": "light-dark(#8b5cf6, #a78bfa)",
    "--color-syntax-variable": "light-dark(#1e293b, #f8fafc)",
    "--color-syntax-operator": "light-dark(#64748b, #94a3b8)",
    "--color-syntax-constant": "light-dark(#f59e0b, #fbbf24)",
    "--color-syntax-tag": "light-dark(#ef4444, #fca5a5)",
    "--color-syntax-attribute": "light-dark(#eab308, #fde047)",
    "--color-syntax-property": "light-dark(#14b8a6, #5eead4)",
    "--color-syntax-punctuation": "light-dark(#94a3b8, #64748b)",
    "--color-syntax-background": "light-dark(#ffffff, #0c0c0c)",
    "--color-background-surface": "light-dark(#ffffff, #171717)",
    "--color-background-body": "light-dark(#f8fafc, #000000)",
    "--color-background-card": "light-dark(#ffffff, #121212)",
    "--color-background-popover": "light-dark(#ffffff, #171717)",
    "--color-background-muted": "light-dark(#f1f5f9, #171717)",
    "--color-accent": "light-dark(#10b981, #72e3ad)",
    "--color-accent-muted": "light-dark(#ecfdf5, #064e3b)",
    "--color-neutral": "light-dark(#0000000F, #FFFFFF1A)",
    "--color-overlay": "light-dark(#00000080, #000000CC)",
    "--color-overlay-hover": "light-dark(#0000000D, #FFFFFF0D)",
    "--color-overlay-pressed": "light-dark(#0000001A, #FFFFFF1A)",
    "--color-text-primary": "light-dark(#0f172a, #f8fafc)",
    "--color-text-secondary": "light-dark(#475569, #94a3b8)",
    "--color-text-disabled": "light-dark(#94a3b8, #475569)",
    "--color-text-accent": "light-dark(#047857, #72e3ad)",
    "--color-on-dark": "#ffffff",
    "--color-on-light": "#0f172a",
    "--color-on-accent": "light-dark(#ffffff, #000000)",
    "--color-on-success": "light-dark(#ffffff, #000000)",
    "--color-on-error": "light-dark(#ffffff, #ffffff)",
    "--color-on-warning": "#0f172a",
    "--color-icon-accent": "light-dark(#10b981, #72e3ad)",
    "--color-icon-primary": "light-dark(#0f172a, #f8fafc)",
    "--color-icon-secondary": "light-dark(#64748b, #94a3b8)",
    "--color-icon-disabled": "light-dark(#94a3b8, #475569)",
    "--color-success": "light-dark(#059669, #3ecf8e)",
    "--color-error": "light-dark(#dc2626, #f87171)",
    "--color-warning": "light-dark(#d97706, #fbbf24)",
    "--color-success-muted": "light-dark(#d1fae5, #064e3b3D)",
    "--color-error-muted": "light-dark(#fee2e2, #7f1d1d3D)",
    "--color-warning-muted": "light-dark(#fef3c7, #78350f3D)",
    "--color-border": "light-dark(#e2e8f0, #262626)",
    "--color-border-emphasized": "light-dark(#cbd5e1, #333333)",
    "--radius-none": "0px",
    "--radius-inner": "4px",
    "--radius-element": "6px",
    "--radius-container": "8px",
    "--radius-page": "12px",
    "--radius-full": "9999px",
    "--shadow-low": "0 1px 2px 0 rgba(0, 0, 0, 0.05), inset 0 0 0 1px light-dark(transparent, rgba(255, 255, 255, 0.08))",
    "--shadow-med": "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1), inset 0 0 0 1px light-dark(transparent, rgba(255, 255, 255, 0.1))",
    "--shadow-high": "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.1), inset 0 0 0 1px light-dark(transparent, rgba(255, 255, 255, 0.12))"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "button": {
      "variant:destructive": {
        "backgroundColor": "var(--color-error-muted)",
        "color": "var(--color-error)"
      }
    },
    "card": {
      "base": {
        "padding": "1rem",
        "borderRadius": "var(--radius-container)",
        "border": "1px solid var(--color-border)"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "var(--color-on-dark)",
      "--color-icon-primary": "var(--color-on-dark)",
      "--color-accent": "var(--color-on-dark)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "var(--color-on-light)",
      "--color-icon-primary": "var(--color-on-light)",
      "--color-accent": "var(--color-on-light)"
    }
  },
  icons: supabaseIconRegistry,
};

export { supabaseIconRegistry };
