/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\themes\supabase\supabaseTheme.ts
 * Command: astryx theme build src\themes\supabase\supabaseTheme.ts
 * CLI: @astryxdesign/cli@0.5.0
 * Core: @astryxdesign/core@0.5.0
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const supabaseIconRegistry: IconRegistry;
export declare const supabaseTheme: DefinedTheme;
